#!/bin/bash
echo Bash is starting

COUNTER = 0
while [ $COUNTER -lt 10]; do
  echo The counter is $COUNTER
  let COUNTER = COUNTER+1
done

COUNTER = 20
untill [ $COUNTER -gt 10]; do
  echo counter $COUNTER
  let COUNTER-=1
done




